@baseUrl = http://localhost:5000

@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "adminmia",
  "password": "mysecret",
  "email": "adminmia@gmail.com",
  "avatarColor": "red",
  "avatarImage": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA0gAAAMyAQMAAABtkHM/AAAABlBMVEUAAAD///+l2Z/dAAAAAXRSTlMAQObYZgAAAAFiS0dEAf8CLd4AAABrSURBVBgZ7cGBAAAAAMOg+1NP4AjVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjgBSwwABwrL8wAAAAABJRU5ErkJggg=="

}

# ###
# POST {{baseUrl}}/{{urlPath}}/signin
# Content-Type: application/json
# Accept: application/json
# withCredentials: true

# {
#   "username": "admin",
#   "password": "123456"
# }

# ###
# GET {{baseUrl}}/{{urlPath}}/signout
# Content-Type: application/json
# Accept: application/json
# withCredentials: true

# ###
# GET {{baseUrl}}/{{urlPath}}/current-user
# Content-Type: application/json
# Accept: application/json
# withCredentials: true

# ###
# POST {{baseUrl}}/{{urlPath}}/forgot-password
# Content-Type: application/json
# Accept: application/json
# withCredentials: true

# {
#   "email": "admin@gmail.com"
# }

# ###
# POST {{baseUrl}}/{{urlPath}}/reset-password/908eb5a9d2320f61786228daa941e40aad4ce46f
# Content-Type: application/json
# Accept: application/json
# withCredentials: true

# {
#   "password": "123456",
#   "confirmPassword": "123456"
# }
